chore(deps): update all dependencies j:cdx-227 (#1084)
[![Mend
Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [@npmcli/arborist](https://togithub.com/npm/cli) | [`6.1.5` ->
`6.1.6`](https://renovatebot.com/diffs/npm/@npmcli%2farborist/6.1.5/6.1.6)
|
[![age](https://badges.renovateapi.com/packages/npm/@npmcli%2farborist/6.1.6/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/@npmcli%2farborist/6.1.6/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/@npmcli%2farborist/6.1.6/compatibility-slim/6.1.5)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/@npmcli%2farborist/6.1.6/confidence-slim/6.1.5)](https://docs.renovatebot.com/merge-confidence/)
|
| [aws-sdk](https://togithub.com/aws/aws-sdk-js) | [`2.1293.0` ->
`2.1295.0`](https://renovatebot.com/diffs/npm/aws-sdk/2.1293.0/2.1295.0)
|
[![age](https://badges.renovateapi.com/packages/npm/aws-sdk/2.1295.0/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/aws-sdk/2.1295.0/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/aws-sdk/2.1295.0/compatibility-slim/2.1293.0)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/aws-sdk/2.1295.0/confidence-slim/2.1293.0)](https://docs.renovatebot.com/merge-confidence/)
|
|
[devtools-protocol](https://togithub.com/ChromeDevTools/devtools-protocol)
| [`0.0.1090008` ->
`0.0.1092731`](https://renovatebot.com/diffs/npm/devtools-protocol/0.0.1090008/0.0.1092731)
|
[![age](https://badges.renovateapi.com/packages/npm/devtools-protocol/0.0.1092731/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/devtools-protocol/0.0.1092731/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/devtools-protocol/0.0.1092731/compatibility-slim/0.0.1090008)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/devtools-protocol/0.0.1092731/confidence-slim/0.0.1090008)](https://docs.renovatebot.com/merge-confidence/)
|
| [eslint](https://eslint.org)
([source](https://togithub.com/eslint/eslint)) | [`8.31.0` ->
`8.32.0`](https://renovatebot.com/diffs/npm/eslint/8.31.0/8.32.0) |
[![age](https://badges.renovateapi.com/packages/npm/eslint/8.32.0/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/eslint/8.32.0/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/eslint/8.32.0/compatibility-slim/8.31.0)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/eslint/8.32.0/confidence-slim/8.31.0)](https://docs.renovatebot.com/merge-confidence/)
|
| [fancy-test](https://togithub.com/oclif/fancy-test) | [`2.0.11` ->
`2.0.12`](https://renovatebot.com/diffs/npm/fancy-test/2.0.11/2.0.12) |
[![age](https://badges.renovateapi.com/packages/npm/fancy-test/2.0.12/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/fancy-test/2.0.12/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/fancy-test/2.0.12/compatibility-slim/2.0.11)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/fancy-test/2.0.12/confidence-slim/2.0.11)](https://docs.renovatebot.com/merge-confidence/)
|
| [prettier](https://prettier.io)
([source](https://togithub.com/prettier/prettier)) | [`2.8.2` ->
`2.8.3`](https://renovatebot.com/diffs/npm/prettier/2.8.2/2.8.3) |
[![age](https://badges.renovateapi.com/packages/npm/prettier/2.8.3/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/prettier/2.8.3/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/prettier/2.8.3/compatibility-slim/2.8.2)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/prettier/2.8.3/confidence-slim/2.8.2)](https://docs.renovatebot.com/merge-confidence/)
|
| [ts-jest](https://kulshekhar.github.io/ts-jest)
([source](https://togithub.com/kulshekhar/ts-jest)) | [`29.0.4` ->
`29.0.5`](https://renovatebot.com/diffs/npm/ts-jest/29.0.4/29.0.5) |
[![age](https://badges.renovateapi.com/packages/npm/ts-jest/29.0.5/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/npm/ts-jest/29.0.5/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/npm/ts-jest/29.0.5/compatibility-slim/29.0.4)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/npm/ts-jest/29.0.5/confidence-slim/29.0.4)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>npm/cli</summary>

###
[`v6.1.6`](https://togithub.com/npm/cli/blob/HEAD/workspaces/arborist/CHANGELOG.md#&#8203;616-httpsgithubcomnpmclicomparearborist-v615arborist-v616-2023-01-12)

[Compare
Source](https://togithub.com/npm/cli/compare/1ceed7b6a762214904ff4a4a08e364153fd1e1dc...868aeb57fbc14870a3338a95fef0e1c6fe0d9b86)

##### Bug Fixes

-
[`b584af0`](https://togithub.com/npm/cli/commit/b584af0237eecd5c32cdab98b8a067798eb25eea)
[#&#8203;6022](https://togithub.com/npm/cli/pull/6022) remove unneeded
param default ([@&#8203;wraithgar](https://togithub.com/wraithgar))
-
[`2ba1171`](https://togithub.com/npm/cli/commit/2ba1171f867bfacedbab056d165d50e58b0cb7ed)
streamline workspace loading code
([@&#8203;wraithgar](https://togithub.com/wraithgar))
-
[`2383deb`](https://togithub.com/npm/cli/commit/2383deb9723593365cf748238f3b2388e7aaf6f5)
[#&#8203;6037](https://togithub.com/npm/cli/pull/6037) clean urls from
arborist, owner, and ping commands
([#&#8203;6037](https://togithub.com/npm/cli/issues/6037))
([@&#8203;lukekarrys](https://togithub.com/lukekarrys))
-
[`c52cf6b`](https://togithub.com/npm/cli/commit/c52cf6bc547268833cde2715fe4f6299240049f8)
[#&#8203;5960](https://togithub.com/npm/cli/pull/5960) properly handle
directory, file, git and alias specs in overrides
([@&#8203;nlf](https://togithub.com/nlf))

</details>

<details>
<summary>aws/aws-sdk-js</summary>

###
[`v2.1295.0`](https://togithub.com/aws/aws-sdk-js/blob/HEAD/CHANGELOG.md#&#8203;212950)

[Compare
Source](https://togithub.com/aws/aws-sdk-js/compare/v2.1294.0...v2.1295.0)

- bugfix: Endpoints: Use correct FIPS endpoint for CloudFormation in
GovCloud
- feature: Connect: This release updates the responses of
UpdateContactFlowContent, UpdateContactFlowMetadata,
UpdateContactFlowName and DeleteContactFlow API with empty responses.
-   feature: EC2: Documentation updates for EC2.
- feature: Outposts: This release adds POWER\_30\_KVA as an option for
PowerDrawKva. PowerDrawKva is part of the RackPhysicalProperties
structure in the CreateSite request.
- feature: ResourceGroups: AWS Resource Groups customers can now turn on
Group Lifecycle Events in their AWS account. When you turn this on,
Resource Groups monitors your groups for changes to group state or
membership. Those changes are sent to Amazon EventBridge as events that
you can respond to using rules you create.

###
[`v2.1294.0`](https://togithub.com/aws/aws-sdk-js/blob/HEAD/CHANGELOG.md#&#8203;212940)

[Compare
Source](https://togithub.com/aws/aws-sdk-js/compare/v2.1293.0...v2.1294.0)

-   feature: CleanRooms: Initial release of AWS Clean Rooms
- feature: CloudWatchLogs: Bug fix: logGroupName is now not a required
field in GetLogEvents, FilterLogEvents, GetLogGroupFields, and
DescribeLogStreams APIs as logGroupIdentifier can be provided instead
- feature: Lambda: Add support for MaximumConcurrency parameter for SQS
event source. Customers can now limit the maximum concurrent invocations
for their SQS Event Source Mapping.
- feature: MediaConvert: The AWS Elemental MediaConvert SDK has added
support for compact DASH manifest generation, audio normalization using
TruePeak measurements, and the ability to clip the sample range in the
color corrector.

</details>

<details>
<summary>ChromeDevTools/devtools-protocol</summary>

###
[`v0.0.1092731`](https://togithub.com/ChromeDevTools/devtools-protocol/compare/v0.0.1092232...v0.0.1092731)

[Compare
Source](https://togithub.com/ChromeDevTools/devtools-protocol/compare/v0.0.1092232...v0.0.1092731)

###
[`v0.0.1092232`](https://togithub.com/ChromeDevTools/devtools-protocol/compare/v0.0.1090008...v0.0.1092232)

[Compare
Source](https://togithub.com/ChromeDevTools/devtools-protocol/compare/v0.0.1090008...v0.0.1092232)

</details>

<details>
<summary>eslint/eslint</summary>

### [`v8.32.0`](https://togithub.com/eslint/eslint/releases/tag/v8.32.0)

[Compare
Source](https://togithub.com/eslint/eslint/compare/v8.31.0...v8.32.0)

#### Features

-
[`fc20f24`](https://togithub.com/eslint/eslint/commit/fc20f242a2ac073b5af6d5fca67e07a175f36c3b)
feat: add suggestions for redundant wrapping in prefer-regex-literals
([#&#8203;16658](https://togithub.com/eslint/eslint/issues/16658))
(YeonJuan)

#### Bug Fixes

-
[`b4f8329`](https://togithub.com/eslint/eslint/commit/b4f8329164d7b293a1557e05b987d2a685fe1d30)
fix: ignore directives for no-fallthrough
([#&#8203;16757](https://togithub.com/eslint/eslint/issues/16757))
(gfyoung)

#### Documentation

-
[`17b65ad`](https://togithub.com/eslint/eslint/commit/17b65ad10d653bb05077f21d8b1f79bee96e38d8)
docs: IA Update page URL move
([#&#8203;16665](https://togithub.com/eslint/eslint/issues/16665)) (Ben
Perlmutter)
-
[`5981296`](https://togithub.com/eslint/eslint/commit/5981296d5c7c86228ad766009901191fdd87d5a4)
docs: fix theme switcher button
([#&#8203;16752](https://togithub.com/eslint/eslint/issues/16752)) (Sam
Chen)
-
[`6669413`](https://togithub.com/eslint/eslint/commit/66694136b67277c050bd27f60050779687a88c9f)
docs: deploy prerelease docs under the `/docs/next/` path
([#&#8203;16541](https://togithub.com/eslint/eslint/issues/16541))
(Nitin Kumar)
-
[`78ecfe0`](https://togithub.com/eslint/eslint/commit/78ecfe0e52c0e5780fefc8dc9a98864e48de6637)
docs: use inline code for rule options name
([#&#8203;16768](https://togithub.com/eslint/eslint/issues/16768))
(Percy Ma)
-
[`fc2ea59`](https://togithub.com/eslint/eslint/commit/fc2ea598aee97beb6d768866da1ee4f63775f0c9)
docs: Update README (GitHub Actions Bot)
-
[`762a872`](https://togithub.com/eslint/eslint/commit/762a8727fb3b5619cff900826053b643ca5f1162)
docs: Update README (GitHub Actions Bot)

#### Chores

-
[`2952d6e`](https://togithub.com/eslint/eslint/commit/2952d6ed95811ce0971b6855d66fb7a9767a7b72)
chore: sync templates/\*.md files with issue templates
([#&#8203;16758](https://togithub.com/eslint/eslint/issues/16758))
(gfyoung)
-
[`3e34418`](https://togithub.com/eslint/eslint/commit/3e34418b31664decfb2337de798feafbf985b66c)
chore: Add new issues to triage project
([#&#8203;16740](https://togithub.com/eslint/eslint/issues/16740))
(Nicholas C. Zakas)

</details>

<details>
<summary>oclif/fancy-test</summary>

###
[`v2.0.12`](https://togithub.com/oclif/fancy-test/releases/tag/2.0.12)

[Compare
Source](https://togithub.com/oclif/fancy-test/compare/2.0.11...2.0.12)

##### Bug Fixes

- **deps:** bump nock from 13.1.0 to 13.3.0
([#&#8203;293](https://togithub.com/oclif/fancy-test/issues/293))
([edd9c6c](https://togithub.com/oclif/fancy-test/commit/edd9c6c41e6d93277e9798e9aa1947b57676b638))

</details>

<details>
<summary>prettier/prettier</summary>

###
[`v2.8.3`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#&#8203;283)

[Compare
Source](https://togithub.com/prettier/prettier/compare/2.8.2...2.8.3)

[diff](https://togithub.com/prettier/prettier/compare/2.8.2...2.8.3)

##### Allow self-closing tags on custom elements
([#&#8203;14170](https://togithub.com/prettier/prettier/pull/14170) by
[@&#8203;fisker](https://togithub.com/fisker))

See [Angular v15.1.0 release
note](https://togithub.com/angular/angular/releases/tag/15.1.0) for
details.

<!-- prettier-ignore -->

```html
// Input
<app-test/>

// Prettier 2.8.2
SyntaxError: Only void and foreign elements can be self closed "app-test" (1:1)
> 1 | <app-test/>
    | ^^^^^^^^^
  2 |

// Prettier 2.8.3
<app-test />
```

</details>

<details>
<summary>kulshekhar/ts-jest</summary>

###
[`v29.0.5`](https://togithub.com/kulshekhar/ts-jest/blob/HEAD/CHANGELOG.md#&#8203;2905-httpsgithubcomkulshekharts-jestcomparev2904v2905-2023-01-13)

[Compare
Source](https://togithub.com/kulshekhar/ts-jest/compare/v29.0.4...v29.0.5)

##### Reverts

- Revert "fix(transformer): don't use cache when `tsJestConfig` is
different
([#&#8203;3966](https://togithub.com/kulshekhar/ts-jest/issues/3966))"
([185eb18](https://togithub.com/kulshekhar/ts-jest/commit/185eb189d7076c717a107066817d2d6959a8fe39)),
closes
[#&#8203;3966](https://togithub.com/kulshekhar/ts-jest/issues/3966)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "before 3am on Monday" (UTC),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config help](https://togithub.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Mend
Renovate](https://www.mend.io/free-developer-tools/renovate/). View
repository job log
[here](https://app.renovatebot.com/dashboard#github/coveo/cli).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNC4xMDAuMSIsInVwZGF0ZWRJblZlciI6IjM0LjEwMi41In0=-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>